### ISSUE TITLE
error while creating a pycsw harvester source

### ISSUE THREAD

**Issue by x-malet** [ckan/ckanext-spatial#220]
![image](https://user-images.githubusercontent.com/7076617/56452569-d61e4000-62ff-11e9-9988-ca8b232a5fd2.png)

I run pycsw and ckan from docker but I got this error while mounting it. I don't really know if there is something I'm doing wrong.

**Comment by x-malet** [comment]
```
ckan     | 2019-04-20 04:12:46,275 INFO  [ckanext.harvest.plugin] Creating harvest source: {'name': u'pycsw', 'title': u'pycsw', 'url': u'http://pycsw:8000/pycsw/csw.py', u'type': u'harvest', 'notes': u'', 'source_type': u'csw', 'frequency': u'MANUAL', 'creator_user_id': u'43352d9a-237b-48b4-a0cd-b4b5159497db', 'config': u'', 'id': '6ba9c994-c079-48e4-a9e7-6c8ab97f09a8', 'extras': [{'value': u'', 'key': 'config'}, {'value': u'MANUAL', 'key': 'frequency'}, {'value': u'csw', 'key': 'source_type'}]}
ckan     | 2019-04-20 04:12:55,972 INFO  [ckanext.harvest.plugin] Harvest source created: 6ba9c994-c079-48e4-a9e7-6c8ab97f09a8
ckan     | 2019-04-20 04:12:56,015 ERROR [ckan.config.middleware.flask_app] 'Package' object has no attribute 'extras_list'
ckan     | Traceback (most recent call last):
ckan     |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
ckan     |     rv = self.dispatch_request()
ckan     |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
ckan     |     return self.view_functions[rule.endpoint](**req.view_args)
ckan     |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
ckan     |     return self.dispatch_request(*args, **kwargs)
ckan     |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
ckan     |     return meth(*args, **kwargs)
ckan     |   File "/usr/lib/ckan/venv/src/ckan/ckan/views/dataset.py", line 521, in post
ckan     |     pkg_dict = get_action(u'package_create')(context, data_dict)
ckan     |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py", line 466, in wrapped
ckan     |     result = _action(context, data_dict, **kw)
ckan     |   File "/usr/lib/ckan/venv/src/ckan/ckan/logic/action/create.py", line 209, in package_create
ckan     |     item.create(pkg)
ckan     |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/ckanext_spatial-0.2-py2.7.egg/ckanext/spatial/plugin.py", line 90, in create
ckan     |     self.check_spatial_extra(package)
ckan     |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/ckanext_spatial-0.2-py2.7.egg/ckanext/spatial/plugin.py", line 107, in check_spatial_extra
ckan     |     for extra in package.extras_list:
ckan     | AttributeError: 'Package' object has no attribute 'extras_list'
```

**Comment by frafra** [comment]
Wy does this issue has been closed? I have the same error.

**Comment by frafra** [comment]
It could be related with: https://github.com/ckan/ckan/commit/e0945313ab34aeb54602caa4046d630491f61252

**Comment by x-malet** [comment]
I closed it because I deployed ckan again and it worked. I thought I was the problem... Lol

**Comment by frafra** [comment]
The problem is still there. You are not using the master version but the 2.8.x instead I suppose.
